<?php
// $Id
define('NOTICIAS_N', 10);
define('NOTICIAS_LATEST_NEWS', 3);

/*  -------------- HOOK SECTION ------------------ */


/**
 * Implementation of hook_menu().
 */
function noticias_menu() {
  $items['noticias'] = array(
    'title' => 'News',
    'page callback' => 'theme',
    'page arguments' => array('noticias'),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_block
 */
function noticias_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
  case 'list':
    $blocks = array();
    $blocks[0] = array(
      'info' => t('Latest news'),
      'cache' => BLOCK_CACHE_GLOBAL,
      'weight' => 0,
      'status' => 1,
      'region' => 'right',
      'visibility' => 1,
      'pages' => '<front>\nnoticias\nnoticia/*'
    );
    return $blocks;
  case 'configure':
  case 'save':
    return;
  case 'view':
    switch ($delta) {
    case 0:
      // Your module will need to define this function to render the block.
      $block = array(
        'content' => noticias_block_latest_news(),
      );
      return $block;
    }
  }
}

/**
 * Implementation of hook_theme
 */
function noticias_theme($existing, $type, $theme, $path) {
  return array(
    'noticias' => array(
      'arguments' => array(),
      'template' => 'noticias',
      'preprocess functions' => array('noticias_preprocess_noticias')
    ),
    'latest_block' => array(
      'arguments' => array('news' => NULL),
      'template' => 'latest_block',
    ),
    'social_share_links' => array(
      'template' => 'social-share-links',
      'arguments' => array('path' => NULL, 'title' => NULL, 'summary' => NULL, 'text' => NULL, 'image' => NULL, 'medium' => NULL, 'campaign' => NULL),
      'preprocess functions' => array('noticias_preprocess_social_share_links')
    )
  );
}


function noticias_preprocess_social_share_links($variables) {
  $global_url_attributes = array('absolute' => TRUE);
  if (isset($variables['medium']) && isset($variables['campaign'])) {
    $global_url_attributes['query'] = array(
      'utm_medium' => $variables['medium'],
      'utm_campaign' => $variables['campaign']
    );
    $facebook_url = url($variables['path'], array_merge_recursive($global_url_attributes, array('query' => array('utm_source' => 'facebook'))));
    $twitter_url = url($variables['path'], array_merge_recursive($global_url_attributes, array('query' => array('utm_source' => 'twitter'))));
    $google_plus_url = url($variables['path'], array_merge_recursive($global_url_attributes, array('query' => array('utm_source' => 'google-plus'))));
  }
  else {
    $facebook_url = $twitter_url = $google_plus_url = url($variables['path'], $global_url_attributes);
  }
  $variables['wrapper_id'] = isset($variables['medium']) ? "list__social-links__{$variables['medium']}" : "list__social-links";
  $variables['facebook_button'] = theme_facebook_share($facebook_url, $variables['title'], $variables['text'] . $facebook_url, $variables['image'], NULL, 'social-link social-link--facebook');
  $variables['twitter_button'] = theme_twitter_share($twitter_url, $variables['summary'], NULL, 'social-link social-link--twitter');
  $variables['google_plus_button'] = theme_google_plus_share($google_plus_url, 'social-link social-link--googleplus');
}


function noticias_block_latest_news() {
  $db_result = noticias_get_latest_news();
  $news = noticias_prepare_news($db_result);
  return theme('latest_block', $news);
}


function noticias_get_latest_news() {
  $sql = "SELECT n.nid, n.title, n.created
    FROM {node} n
    WHERE n.type = 'noticia' AND n.status = 1
    ORDER BY n.created DESC";
return db_query_range($sql, NOTICIAS_LATEST_NEWS);
}


function noticias_prepare_news($db_result) {
  $news = array();
  while ($res = db_fetch_object($db_result)) {
    $news[] = array(
      'link' => l($res->title, "node/$res->nid"),
      'date' => date('d/m/Y', $res->created)
    );
  }
  return $news;
}


function noticias_get_noticias() {
  $sql = "SELECT n.nid, n.title, f.filepath, n.created, nn.drophead
    FROM {node} n
    INNER JOIN {noticias} nn ON nn.nid = n.nid
    LEFT JOIN {image_attach} im ON n.nid = im.nid
    LEFT JOIN {image} i ON im.iid = i.nid AND i.image_size = '_original'
    LEFT JOIN {files} f ON f.fid = i.fid
    WHERE n.type = 'noticia' AND n.status = 1
    ORDER BY n.created DESC";
return $sql;
}


function noticias_preprocess_noticias(&$vars) {
  $sql = noticias_get_noticias();
  $result = pager_query($sql);
  while($res = db_fetch_array($result)) {
    $vars['noticias'][]=$res;
  }
  $vars['pager'] = theme('pager');
}


function noticias_preprocess_node(&$variables) {
  if (isset($variables['image_attach']) && !empty($variables['image_attach'])) {
    $image = current($variables['image_attach']);
    $variables['picture'] = theme('image', $image->images['_original'], $image->title, $image->title);
  }
}


function noticias_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'noticia_node_form') {
    $form['drophead'] = array(
      '#type' => 'textarea',
      '#title' => t('Summary to frontpage'),
      '#weight' => $form['title']['#weight'] + 1,
      '#default_value' => isset($form['#node']) ? $form['#node']->drophead : ''
    );
  }
}


function noticias_nodeapi($node, $op) {
  if ($node->type == 'noticia') {
    if ($op == 'insert' || $op == 'update') {
      db_query("INSERT INTO {noticias} (nid, drophead) VALUES (%d, '%s') ON DUPLICATE KEY UPDATE drophead = '%s'", $node->nid, $node->drophead, $node->drophead);
    }
    if ($op == 'load') {
      $additions = db_fetch_array(db_query("SELECT drophead FROM {noticias} WHERE nid = %d", $node->nid));

      return $additions;
    }
  }
}
