<?php

define('TRACK_RECORD_GOLD_MEDAL', 0);
define('TRACK_RECORD_SILVER_MEDAL', 1);
define('TRACK_RECORD_BRONZE_MEDAL', 2);

function debug($message) {
  return drupal_set_message('<pre>' . print_r($message, TRUE) . '</pre>');
}

function track_record_perm() {
  return array('view track record', 'admin track record');
}

function track_record_menu() {
  $items = array();
  $items['track_record'] = array(
    'title' => 'Track record',
    'description' => 'Shows all the track records of clubs and athletes',
    'page callback' => 'track_record_page',
    'page arguments' => array(),
    'access arguments' => array('view track record'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['track_record/club'] = array(
    'title' => 'Club track record',
    'description' => 'The club track record',
    'page callback' => 'track_record_club_page',
    'page arguments' => array(),
    'access arguments' => array('view track record'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['track_record/%'] = array(
    'title' => 'Athlete track record',
    'description' => 'The athletes track record',
    'page callback' => 'track_record_athlete_page',
    'page arguments' => array(1),
    'access arguments' => array('view track record'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/track_record'] = array(
    'title' => 'Track record',
    'page callback' => 'track_record_admin_page',
    'page arguments' => array(),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/track_record/club'] = array(
    'title' => 'Club administration',
    'page callback' => 'track_record_club_admin_page',
    'page arguments' => array(),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/track_record/club/records'] = array(
    'title' => 'Club track record administration',
    'page callback' => 'track_record_club_records_admin_page',
    'page arguments' => array(),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/track_record/club/records/%'] = array(
    'title' => 'Edit club track record',
    'page callback' => 'track_record_edit_club_record_admin_page',
    'page arguments' => array(4),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/track_record/athletes'] = array(
    'title' => 'Athletes administration',
    'page callback' => 'track_record_athletes_admin_page',
    'page arguments' => array(),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/track_record/athletes/%'] = array(
    'title' => 'Athlete administration',
    'page callback' => 'track_record_athlete_admin_page',
    'page arguments' => array(3),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/track_record/athletes/%/records'] = array(
    'title' => 'Athlete track record administration',
    'page callback' => 'track_record_athlete_records_admin_page',
    'page arguments' => array(3),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK
  );
  $items['admin/track_record/athletes/%/records/%'] = array(
    'title' => 'Edit athlete track record',
    'page callback' => 'track_record_athlete_update_record_admin_page',
    'page arguments' => array(5),
    'access arguments' => array('admin track record'),
    'file' => 'track_record.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK
  );

  return $items;
}


function track_record_page() {
  $club = track_record_get_club_information();
  $athletes = track_record_get_athletes_information();

  return theme('track_record_main', $club, $athletes);
}


function track_record_club_page() {
  $club = track_record_get_club_information();
  $records = track_record_get_club_records($club);

  return theme('track_record_club', $club, $records);
}


function track_record_athlete_page($athlete_id) {
  $athlete = track_record_get_athlete_information($athlete_id);

  return theme('track_record_athlete', $athlete, $athlete['records']);
}


function track_record_theme($existing, $type, $theme, $path) {
  $items = array();
  $items['track_record_main'] = array(
    'template' => 'track_record_main',
    'arguments' => array('club' => NULL, 'athletes' => array())
  );
  $items['track_record_club'] = array(
    'template' => 'track_record_club',
    'arguments' => array('club' => NULL, 'records' => array())
  );
  $items['track_record_club_summary'] = array(
    'template' => 'track_record_club_summary',
    'arguments' => array('club' => NULL)
  );
  $items['track_record_athletes'] = array(
    'template' => 'track_record_athletes',
    'arguments' => array('athletes' => array())
  );
  $items['track_record_athlete'] = array(
    'template' => 'track_record_athlete',
    'arguments' => array('athlete' => NULL, 'records' => array())
  );
  $items['track_record_single_record'] = array(
    'template' => 'track_record_single_record',
    'arguments' => array('medal' => NULL, 'title' => NULL)
  );
  $items['track_record_athlete_photo'] = array(
    'arguments' => array('athlete' => NULL),
    'function' => 'track_record_theme_athlete_photo'
  );
  $items['track_record_club_photo'] = array(
    'arguments' => array('club' => NULL),
    'function' => 'track_record_theme_club_photo'
  );
  $items['track_record_header'] = array(
    'arguments' => array('club' => NULL),
    'template' => 'track_record_header'
  );
  $items['track_record_admin_page'] = array(
    'template' => 'track_record_admin_page',
    'arguments' => array()
  );

  return $items;
}


function track_record_preprocess_page(&$variables) {
  if (in_array('page-track_record', $variables['template_files'])) {
    $club = track_record_get_club_information();
    $variables['content_top'] = theme('track_record_header', $club);
    $variables['extra_class'] = 'track_record';
  }
}


function track_record_imagecache_default_presets() {
  $items = array();
  $items['track_record_summary'] = array(
    'presetname' => 'track_record_summary',
    'actions' => array(
      array(
        'weight' => 0,
        'module' => 'track_record',
        'action' => 'imagecache_scale',
        'data' => array(
          'width' => '130',
          'height' => '130',
          'upscale' => 0,
        )
      )
    )
  );
  $items['track_record_club'] = array(
    'presetname' => 'track_record_club',
    'actions' => array(
      array(
        'weight' => 0,
        'module' => 'track_record',
        'action' => 'imagecache_scale',
        'data' => array(
          'width' => '938',
          'upscale' => 0,
        )
      )
    )
  );

  return $items;
}


function track_record_get_ages($timestamp) {
  return floor((time() - $timestamp)/31556926);
}


function track_record_preprocess_track_record_club(&$variables) {
  $variables['medals'] = track_record_get_medals();
}


function track_record_preprocess_track_record_club_summary(&$variables) {
  $variables['medals'] = track_record_get_medals();
}


function track_record_preprocess_track_record_athletes(&$variables) {
  $variables['medals'] = track_record_get_medals();
}


function track_record_preprocess_track_record_athlete(&$variables) {
  $variables['medals'] = track_record_get_medals();
}


function track_record_theme_athlete_photo(array $athlete) {
  $photo = $athlete['photo'];
  if (!is_null($photo)) {
    return theme('imagecache', 'track_record_summary', $photo, $athlete['name'], $athlete['name']);
  }

  return theme('image', drupal_get_path('module', 'track_record') . '/images/default.jpg', $athlete['name'], $athlete['name']);
}


function track_record_theme_club_photo(array $club) {
  $photo = $club['photo'];
  if (!is_null($photo)) {
    return theme('imagecache', 'track_record_club', $photo, $club['name'], $club['name']);
  }

  return theme('image', drupal_get_path('theme', 'olimpo') . '/images/original_logo.png', $club['name'], $club['name']);
}


function track_record_get_medals() {
  $medals = array(
    TRACK_RECORD_GOLD_MEDAL => 'gold',
    TRACK_RECORD_SILVER_MEDAL => 'silver',
    TRACK_RECORD_BRONZE_MEDAL => 'bronze',
  );

  return $medals;
}


function track_record_get_medal($medal) {
  static $medals;

  if (empty($medals)) {
    $medals = track_record_get_medals();
  }

  return $medals[$medal];
}


function track_record_get_club_information() {
  static $club = array();

  if (empty($club)) {
    $club = db_fetch_array(db_query("SELECT c.*, f.filepath as photo FROM {track_record_clubs} c LEFT JOIN {files} f ON f.fid = c.photo_id WHERE id = 1"));
    $club['records'] = track_record_get_club_records($club);
    $club['track_record_summary'] = track_record_get_record_summary($club['records']);
  }

  return $club;
}


function track_record_get_club_records(array $club) {
  $records = array();
  $results = db_query("SELECT * FROM {track_record_club_records} WHERE club_id = %d ORDER BY weight DESC", $club['id']);
  while ($record = db_fetch_array($results)) {
    $records[] = $record;
  }

  return $records;
}


function track_record_get_club_record_information($record_id) {
  return db_fetch_array(db_query("SELECT * FROM {track_record_club_records} WHERE id = %d", $record_id));
}


function track_record_get_athletes_information() {
  $athletes = array();
  $results = db_query("SELECT a.*, f.filepath as photo FROM {track_record_athletes} a LEFT JOIN {files} f ON f.fid = a.photo_id");
  while ($athlete = db_fetch_array($results)) {
    $athlete['records'] = track_record_get_athlete_records($athlete);
    $athlete['track_record_summary'] = track_record_get_record_summary($athlete['records']);
    $athletes[] = $athlete;
  }

  return $athletes;
}


function track_record_get_athlete_information($id) {
  $athlete = db_fetch_array(db_query("SELECT a.*, f.filepath as photo FROM {track_record_athletes} a LEFT JOIN {files} f ON f.fid = a.photo_id WHERE id = %d", $id));
  $athlete['records'] = track_record_get_athlete_records($athlete);
  $athlete['track_record_summary'] = track_record_get_record_summary($athlete['records']);

  return $athlete;
}


function track_record_get_athlete_records(array $athlete) {
  $records = array();
  $results = db_query("SELECT * FROM {track_record_athlete_records} WHERE athlete_id = %d ORDER BY weight DESC", $athlete['id']);
  while ($record = db_fetch_array($results)) {
    $records[] = $record;
  }

  return $records;
}


function track_record_get_athlete_record_information($record_id) {
  return db_fetch_array(db_query("SELECT * FROM {track_record_athlete_records} WHERE id = %d", $record_id));
}


function track_record_get_record_summary(array $records) {
  $summary = array(
    TRACK_RECORD_GOLD_MEDAL => 0,
    TRACK_RECORD_SILVER_MEDAL => 0,
    TRACK_RECORD_BRONZE_MEDAL => 0
  );
  foreach ($records as $record) {
    $summary[$record['medal']] += 1;
  }

  return $summary;
}
